/* DO NOT EDIT THIS FILE - generated manually according to javac -h output format. */
#include <jni.h>
#ifndef _Included_ua_khpi_oop_lab16_NativeBookingStatistics
#define _Included_ua_khpi_oop_lab16_NativeBookingStatistics
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jdouble JNICALL Java_ua_khpi_oop_lab16_NativeBookingStatistics_average
  (JNIEnv *, jobject, jintArray);
#ifdef __cplusplus
}
#endif
#endif
